services:

  mysql:
    image: mysql:8.0
    container_name: sales_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sales_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: codebytalhadev/sales-server:latest
    container_name: sales_server
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sales_network

  client:
    image: codebytalhadev/sales-client:latest
    container_name: sales_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - sales_network

volumes:
  mysql_data:

networks:
  sales_network:
    driver: bridge