import Product from "../src/models/Product.js";

const seedProduct = async () => {
  await Product.bulkCreate(
    [
      {
        productName: "Sugar",
        barcode: "BAR1001",
        autoGenerateBarcode: false,
        categoryId: 1,
        uomId: 1,
        purchasePrice: 160,
        salePrice: 180,
        manageInventory: true,
        quantity: 100,
        reorderQuantity: 20,
        hasExpiryDate: false,
        expiryDate: null,
        description: "Premium Sugar",
        image: null,
        status: "Y",
      },
      {
        productName: "Rice",
        barcode: "BAR1002",
        autoGenerateBarcode: false,
        categoryId: 1,
        uomId: 1,
        purchasePrice: 240,
        salePrice: 280,
        manageInventory: true,
        quantity: 150,
        reorderQuantity: 30,
        hasExpiryDate: false,
        expiryDate: null,
        description: "Basmati Rice",
        image: null,
        status: "Y",
      },
      {
        productName: "Milk",
        barcode: "BAR1003",
        autoGenerateBarcode: false,
        categoryId: 3,
        uomId: 3,
        purchasePrice: 180,
        salePrice: 220,
        manageInventory: true,
        quantity: 10,
        reorderQuantity: 20,
        hasExpiryDate: true,
        expiryDate: "2026-08-10",
        description: "Fresh Milk",
        image: null,
        status: "Y",
      },
      {
        productName: "Pepsi",
        barcode: "BAR1004",
        autoGenerateBarcode: false,
        categoryId: 2,
        uomId: 5,
        purchasePrice: 90,
        salePrice: 120,
        manageInventory: true,
        quantity: 5,
        reorderQuantity: 15,
        hasExpiryDate: true,
        expiryDate: "2027-01-01",
        description: "Soft Drink",
        image: null,
        status: "Y",
      },
      {
        productName: "Bread",
        barcode: "BAR1005",
        autoGenerateBarcode: false,
        categoryId: 5,
        uomId: 5,
        purchasePrice: 70,
        salePrice: 90,
        manageInventory: true,
        quantity: 15,
        reorderQuantity: 20,
        hasExpiryDate: true,
        expiryDate: "2026-07-20",
        description: "Fresh Bread",
        image: null,
        status: "Y",
      },
      {
        productName: "Biscuits",
        barcode: "BAR1006",
        autoGenerateBarcode: false,
        categoryId: 4,
        uomId: 7,
        purchasePrice: 40,
        salePrice: 60,
        manageInventory: true,
        quantity: 80,
        reorderQuantity: 25,
        hasExpiryDate: true,
        expiryDate: "2026-12-01",
        description: "Chocolate Biscuits",
        image: null,
        status: "Y",
      },
      {
        productName: "Soap",
        barcode: "BAR1007",
        autoGenerateBarcode: false,
        categoryId: 6,
        uomId: 5,
        purchasePrice: 150,
        salePrice: 180,
        manageInventory: true,
        quantity: 50,
        reorderQuantity: 10,
        hasExpiryDate: false,
        expiryDate: null,
        description: "Bath Soap",
        image: null,
        status: "Y",
      },
      {
        productName: "Notebook",
        barcode: "BAR1008",
        autoGenerateBarcode: false,
        categoryId: 7,
        uomId: 5,
        purchasePrice: 200,
        salePrice: 250,
        manageInventory: true,
        quantity: 70,
        reorderQuantity: 15,
        hasExpiryDate: false,
        expiryDate: null,
        description: "A4 Notebook",
        image: null,
        status: "Y",
      },
      {
        productName: "Detergent",
        barcode: "BAR1009",
        autoGenerateBarcode: false,
        categoryId: 10,
        uomId: 5,
        purchasePrice: 350,
        salePrice: 420,
        manageInventory: true,
        quantity: 30,
        reorderQuantity: 10,
        hasExpiryDate: false,
        expiryDate: null,
        description: "Washing Powder",
        image: null,
        status: "Y",
      },
      {
        productName: "Ice Cream",
        barcode: "BAR1010",
        autoGenerateBarcode: false,
        categoryId: 8,
        uomId: 5,
        purchasePrice: 180,
        salePrice: 250,
        manageInventory: true,
        quantity: 12,
        reorderQuantity: 20,
        hasExpiryDate: true,
        expiryDate: "2026-09-15",
        description: "Vanilla Ice Cream",
        image: null,
        status: "Y",
      },
    ],
    {
      ignoreDuplicates: true,
    }
  );

  console.log("✅ Product Seeder Completed");
};

export default seedProduct;