export const CONFLICT_TYPES = Object.freeze({
  VERSION: "VERSION_CONFLICT",

  DELETE: "DELETE_CONFLICT",

  DUPLICATE: "DUPLICATE_CONFLICT",

  SERVER_CHANGED: "SERVER_CHANGED",

  LOCAL_CHANGED: "LOCAL_CHANGED",
});